name: "Notebook Tests"

on:
  push:
  pull_request:
    branches:
      - develop

defaults:
  run:
    shell: bash -l {0}

jobs:
  notebook_tests:
    name: Notebook Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9, "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Workflow Repository
        uses: actions/checkout@v4
      - name: Checkout Environment Repository
        uses: actions/checkout@v4
        with:
          repository: morganjwilliams/im4nis-workshop-env
          path: workshop-env
      - name: setup-micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: workshop-env/binder/environment.yml
          cache-downloads: true
          # cache-environment: true
          create-args: >-
            python=${{ matrix.python-version }}
      - name: Run notebooks
        run: |
          python ./test/run_notebooks.py
